version: 2
jobs:
  build:
    environment:
      GOPATH: /home/circleci/go
    docker:
      - image: circleci/golang:1.12
    working_directory: /home/circleci/go/src/github.com/mzumi/gh-review
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go get -v -t -d ./...
      - run: go get golang.org/x/lint/golint
      - run: go get github.com/haya14busa/goverage
      - run: golint ./...
      - run: go vet ./...
      - run: go test -v -race ./...
  deploy:
    environment:
      GOPATH: /home/circleci/go
    docker:
      - image: circleci/golang:1.12
    working_directory: /home/circleci/go/src/github.com/mzumi/gh-review
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run:
          name: cross compile
          command: |
            gox -os="linux darwin windows" -arch="amd64" -output="dist/gh-review_{{.OS}}_{{.Arch}}"
            cd dist/
            for f in `ls gh-review_*`; do
              if [[ $f =~ windows ]]; then
                ext=".exe"
              else
                ext=""
              fi
            mv $f gh-review$ext
            zip $f.zip gh-review$ext
            rm gh-review$ext
            done

      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG dist/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
